name: Create report from latest benchmark workflows

permissions:
  actions: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      github_workflows_ids:
        description: "Comma-separated list of GitHub workflows ids to use to create the report"
        required: false
        default: ""
        type: string
      circleci_workflows_ids:
        description: "Comma-separated list of CircleCI workflows ids to use to create the report"
        required: false
        default: ""
        type: string

jobs:
  create-report-from-latest-workflows:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CIRCLE_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 🔧
        uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          pip install -r requirements-poetry.txt
          poetry install

      - name: Create report
        run: |
          args=""
          if [[ ! -z "${{ inputs.github_workflows_ids }}" ]]; then
            args="--github ${{ inputs.github_workflows_ids }}"
          fi
          if [[ ! -z "${{ inputs.circleci_workflows_ids }}" ]]; then
            args=$args" --circleci ${{ inputs.circleci_workflows_ids }}"
          fi

          poetry run create-benchmark-report api $args

      - name: Setup Google Auth 🔧
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_DOCS_CREDENTIAL_JSON }}"

      - name: Upload benchmark file to GCP 🚀
        uses: google-github-actions/upload-cloud-storage@v1.0.3
        with:
          path: ci_benchmark_tooling/benchmark_data.csv
          destination: ci-benchmark
          parent: false
          process_gcloudignore: false
          resumable: false
          headers: |-
            cache-control: no-cache
